{ pkgs
, src
, crate-src
, crate-name
, pname ? "cxxbridge-${crate-name}"
}:
pkgs.runCommandLocal pname {} ''
  # Copy over the sources generated by cxx
  mkdir $out
  cp -r ${src}/sources $out/sources

  # Copy over the include headers generated
  mkdir -p $out/include

  ## we move to src so that find returns path relative to it
  ## otherwise it'd return absolute paths
  cd ${src}
  for HEADER in `find ./include -name "*.h" -type f`; do
      ## make sure the folder exists
      mkdir -p $out/$(dirname $HEADER)

      ## we copy with --parents to keep the structure
      ## and since we are copying from the store
      ## we'd be copying with root permissions (so we can't write it!)
      cp --parents --no-preserve=ownership $HEADER $out/
  done
  # (restore folder before our cd to src)
  cd ..

  ## and create the .rs links that would normally be there
  ## but we need to have them pointing at the store instead
  INCLUDES=`find $out/include -name "*.h" -type f`
  for INC in $INCLUDES; do
    ln -s ./$(basename $INC) ''${INC%.*}
  done

  # Recreate crate link (to point to the store)
  # which is expected in to be used in the include paths
  mkdir -p $out/crate
  ln -s ${crate-src} $out/crate/${crate-name}
''
